on:
  push:
    branches:
      - main #ブランチ名
name: Build and Deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action # JOBの名前
    runs-on: ubuntu-latest # 仮想環境の種類を指定
    steps:
      - uses: actions/checkout@v3 
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0 #最新のバージョンを使用
        with:
          server: ${{ secrets.FTP_SERVER }} #FTPサーバーのホスト
          username: ${{ secrets.FTP_USERNAME }} #FTPサーバーのアカウント名
          password: ${{ secrets.FTP_PASSWORD }} #FTPサーバーのパスワード
          protocol: ftps #FTPSで接続する
          port: 21 #ポート番号
          local-dir: ./ #ローカルのディレクトリ
          server-dir: ${{ secrets.REMOTE_DIR }} #デプロイ対象のディレクトリ
          exclude: "[
            .gitignore,
            **/.git*,
            **/.git/**,
            **/.git*/**,
            **/node_modules/**,
            **/vendor/**,
            .editorconfig,
            README.md,
            docker,
            develop/**,
            css/**,
            image/**,
            template-parts/**.
            ]"